#! /usr/bin/env bash

sudo apt-get update

# linux packages (when available via apt)
sudo apt-get install -y tldr zsh ctags

# vim
cd && mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# vim plugins
cd ~/.vim/bundle
git clone https://github.com/junegunn/fzf
git clone https://github.com/junegunn/fzf.vim
git clone https://github.com/vim-airline/vim-airline
git clone https://github.com/tpope/vim-fugitive
git clone https://github.com/jeetsukumaran/vim-indentwise
git clone https://github.com/tpope/vim-rails

cd && wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
CHSH=no sh install.sh

# dotfiles
cd && git clone -b main https://github.com/samcambridge/dotfiles ~/.dotfiles
cd ~/.dotfiles && cp .bash_profile .gitconfig .vimrc .zshrc ~/

# zsh
source ~/.zshrc
cd ~/.dotfiles && git clone https://github.com/romkatv/powerlevel10k.git

# return to home folder
cd
