#! /usr/bin/env bash

sudo apt-get update

# linux packages (when not available via apt)
cd && curl -LO https://github.com/sharkdp/fd/releases/download/v8.2.1/fd_8.2.1_amd64.deb
sudo dpkg -i fd_8.2.1_amd64.deb
curl -LO https://github.com/BurntSushi/ripgrep/releases/download/12.1.1/ripgrep_12.1.1_amd64.deb
sudo dpkg -i ripgrep_12.1.1_amd64.deb
curl -LO http://ftp.pl.debian.org/debian/pool/main/f/fzf/fzf_0.24.3-1+b5_amd64.deb
sudo dpkg -i fzf_0.24.3-1+b5_amd64.deb
rm ~/*.deb

# linux packages (when available via apt)
sudo apt-get install -y tldr zsh ctags

# vim
cd && mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# vim plugins
cd ~/.vim/bundle
git clone https://github.com/junegunn/fzf
git clone https://github.com/junegunn/fzf.vim
git clone https://github.com/vim-airline/vim-airline
git clone https://github.com/tpope/vim-fugitive
git clone https://github.com/jeetsukumaran/vim-indentwise
git clone https://github.com/tpope/vim-rails

# dotfiles
cd && git clone -b sandbox https://github.com/vysogot/dotfiles ~/.dotfiles
cd ~/.dotfiles && cp .gemrc .bash_profile .gitconfig .vimrc ~/

# zsh
cd ~/.dotfiles && cp .zshrc .p10k.zsh ~/ && git clone https://github.com/romkatv/powerlevel10k.git

# visual studio live share
sudo apt install libssl1.0.0 libkrb5-3 zlib1g libicu[0-9][0-9] gnome-keyring libsecret-1-0 desktop-file-utils x11-utils


# return to home folder
cd
